name: Hetzner server static-site Push Update

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [latest-website]
  workflow_dispatch:

jobs:
  pull_website_to_server:
    name: Pull latest version of website
    runs-on: ubuntu-latest
    steps:
    - name: Connect to Tailscale network to allow access to server
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
        tags: ${{ secrets.TAILSCALE_DEVICE_TAG }}

    - name: Checkout the Repo
      uses: actions/checkout@v4

    - name: Push to live site
      if: github.event_name == 'push' && github.event.branch == 'main'
      run: |
        git config user.name ${{ vars.USER_NAME  }}
        git config user.email ${{ vars.EMAIL_ADDRESS }}
        git remote add live ssh://amosley@5.161.65.90:/var/repos/ajmosley.com.git
        git push live
    
    - name: Do an empty commit and push to new webserver
      if: github.event_name == 'repository_dispatch'
      run: |
        git config user.name ${{ vars.USER_NAME  }}
        git config user.email ${{ vars.EMAIL_ADDRESS }}
        git remote add live ssh://${{ vars.SSH_USER }}@${{ vars.WEBSERVER_NAME }}:${{ secrets.WEBSITE_REPO }}
        git commit --allow-empty -m "Trigger live website update for first push"
        git push live