name: Hetzner server static-site Push Update

on:
#   push:
#     branches:
#       - main
    workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Prepare ssh keys
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.AM_STATIC_SITE_KEY }}
        known_hosts: ${{ secrets.AM_STATIC_SITE_KNOWN_HOSTS }}

    - name: Checkout the Repo
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.AM_STATIC_SITE_KEY }}
        fetch-depth: 0
        ref: master
    - name: Push to cloud webserver
      run: |
        git config user.name ajmosley345
        git config user.email ajmosley345@gmail.com
        git remote add prod ssh://amosley@5.161.65.90:/var/repos/ajmosley.com.git
        git push prod